services:
  postgres:
    restart: always
    image: postgres:16-bullseye
    networks:
      - db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      timeout: 2s
      interval: 5s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: shyim/adminerevo:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

  # test-server:
  #   image: test-server:latest
  #   profiles: ["test"]
  #   networks:
  #     - db
  #   command: pytest

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local
