services:
  postgres:
    restart: always
    image: postgres:16-bullseye
    networks:
      - db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      timeout: 2s
      interval: 5s
      retries: 10
    ports:
      - 5432:5432

  adminer:
    image: shyim/adminerevo:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

  test-server:
    image: test-server:latest
    profiles: ["test"]
    environment:
      - ENVIRONEMNT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - DB_PORT
    networks:
      - db
    command: pytest

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local
