[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = [
    "tests"
]
filterwarnings = "ignore"
log_file = "pytest.log"
log_file_level = "DEBUG"
log_file_format = "[%(levelname)-8s : %(asctime)s] %(name)s - %(message)s"
log_file_date_format = "%Y-%m-%d %H:%M:%S"
